# Base lightweight Python image
FROM python:3.13-slim

# Set working directory inside the container
WORKDIR /app

# Copy dependency list first (better Docker layer caching)
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project into the container
COPY . .

# Run ONLY API tests
CMD ["pytest", "-v", "api_tests"]
